---
- name: k8s-cluster
  hosts: master, node1, node2
  become: true
  gather_facts: true
  roles:
    - 1_kube-prerequisites
    - 2_containerd
    - 3_kubelet-kubeadm-kubectl
  
- name: init-cluster
  hosts: master
  become: true
  gather_facts: true
  roles:
    - 4_init-cluster
    
- name: add workers
  hosts: node1, node2
  become: true
  gather_facts: true
  roles:
    - 5_add-workers

#- name: Install node-exporter
#  hosts: master, node1, node2, vm
#  become: true
#  gather_facts: true
#  roles:
#    - 6_node-exporter

#- name: Install prometheus-grafana
#  hosts: master
#  become: true
#  gather_facts: true
#  roles:    
#    - 7_prometheus-grafana
