---
- name: k8s-cluster
  hosts: master, node1, node2
  become: true
  gather_facts: true
  roles:
    - 1_kube-prerequisites
    - 2_containerd
    - 3_kubelet-kubeadm-kubectl
  
- name: init-cluster
  hosts: master
  become: true
  gather_facts: true
  roles:
    - 4_init-cluster
    
- name: add workers
  hosts: node1, node2
  become: true
  gather_facts: true
  roles:
    - 5_add-workers

- name: Install helm
  hosts: master
  become: true
  gather_facts: true
  roles:
    - 6_install-helm

- name: Install kube-prometheus-stack
  hosts: master
  become: true
  gather_facts: true
  roles:    
    - 7_helm-install-kube-prom-stack
    
- name: Install node-exporter
  hosts: vm
  become: true
  gather_facts: true
  roles:    
    - 8_install-node-exporter
