---
- name: Add stable chart repo nginx-ingress
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"

- name: Copy values.yaml
  ansible.builtin.copy:
    src: ../files/values.yaml
    dest: $PWD

- name: Deploy ingress-nginx version 4.11.2 inside monitoring namespace
  kubernetes.core.helm:
    update_repo_cache: true
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: 4.11.2
    release_namespace: monitoring
    values_files:
      - /home/ilya/values.yaml
