---
- name: Copy values.yaml
  ansible.builtin.copy:
    src: ../files/scrapeconfig.yaml
    dest: /tmp/scrapeconfig.yaml

- name: Create a ScrapeConfig from a local file
  kubernetes.core.k8s:
    state: present
    src: /tmp/scrapeconfig.yaml
