---
- name: add Kubernetes apt-key
  apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    state: present

- name: add Kubernetes' APT repository
  become: true
  apt_repository:
    repo: deb https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
    state: present
    filename: 'kubernetes'

- name: Update APT Cache
  apt:
    update_cache: yes

- name: Remove apt lock-frontend file
  file:
    state: absent
    path: "/var/lib/dpkg/lock-frontend"

- name: install Kubelet
  become: true
  apt:
    name: kubelet=1.28.*
    state: present

- name: install Kubeadm
  become: true
  apt:
    name: kubeadm=1.28.*
    state: present

- name: install kubectl
  become: true
  apt:
    name: kubectl=1.28.*
    state: present

- name: hold kubeadm kubeadm kubectl
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl
